name: Build ExpenShare

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-2025
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
  
    steps:
      # 1. Check out the repository code
      - name: Checkout Code
        uses: actions/checkout@v7

      # 2. Setup Node.js environment
      - uses: pnpm/setup@v2

      # 3. Build the application (Electron Forge make)
      # This runs the 'make' script from your package.json
      - name: Build
        run: pnpm run publish